---
kind: Parameter
name: value
version: 1
datainfo: numeric
readonly: true
description: |
  The value parameter.

---
kind: Parameter
name: status
version: 1
datainfo: tuple of status-code, message
readonly: true
description: |
  The status parameter.

---
kind: Parameter
name: target
version: 1
datainfo: numeric
readonly: false
description: |
  The target value for the module. By setting this parameter, a move
  operation is started.

---
kind: Parameter
name: pollinterval
version: 1
datainfo: double
description: |
  Hint for polling interval in seconds.

---
kind: Parameter
name: offset
version: 1
datainfo: numeric
readonly: false
description: |
  Offset parameter for the HasOffset feature.

---
kind: Parameter
name: target_limits
version: 1
datainfo: tuple numeric, numeric
readonly: true
description: |
  Changeble user-defined limits for the target parameter of a module.
  Has to respect the limits of the target parameter itself.

---
kind: Parameter
name: ramp
version: 1
datainfo: numeric
readonly: false
description: |
  Desired ramp. Unit is main-unit/min.

---
kind: Parameter
name: setpoint
version: 1
datainfo: numeric
readonly: true
description: |
  ramping setpoint

---
kind: Parameter
name: time_to_target
version: 1
datainfo: numeric
readonly: true
description: |
  Expected time to reach the target in seconds

---
kind: Parameter
name: controlled_by
version: 1
datainfo: string
readonly: false
description: |
  indicates the module this modules value is controlled by.

---
kind: Parameter
name: control_active
version: 1
datainfo: boolean
readonly: true
description: |
  Indicates whether this module is actively controlling.
